# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo VITE_APIKEY=${{ secrets.VITE_APIKEY }} >> .env
          echo VITE_AUTHDOMAIN=${{ secrets.VITE_AUTHDOMAIN }} >> .env
          echo VITE_PROJECTID=${{ secrets.VITE_PROJECTID }} >> .env
          echo VITE_STORAGEBUCKET=${{ secrets.VITE_STORAGEBUCKET }} >> .env
          echo VITE_MESSAGINGSENDERID=${{ secrets.VITE_MESSAGINGSENDERID }} >> .env
          echo VITE_APPID=${{ secrets.VITE_APPID }} >> .env
          echo VITE_MEASUREMENTID=${{ secrets.VITE_MEASUREMENTID }} >> .env
          echo Created .env file

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DARKMODENOW_72BC9 }}
          channelId: live
          projectId: darkmodenow-72bc9
